title: Rano's Portfolio
description: Aspiring Data Scientist
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# --- YOUR PERSONAL LINKS ---
email: dasranojoy9@gmail.com
linkedin: https://www.linkedin.com/in/ranojoy-das/
github_handle: https://github.com/IamRaNo
twitter: https://x.com/i_am_rano_3
blogger: https://thetshooter.blogspot.com/
leetcode: https://leetcode.com/u/iamrano/
hackerrank: https://www.hackerrank.com/profile/dasranojoy9
kaggle: https://www.kaggle.com/myselfranoranojoy
facebook: https://www.facebook.com/rano.joy.333/
instagram: https://www.instagram.com/forgotten_humanbeing/
